import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton, SignIn } from '@clerk/nextjs';
import { AI } from './actions';
import './globals.css';
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next AI chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AI>
        <html lang="en">
          <body className={clsx(inter.className, 'h-screen')}>
            <header className='flex justify-between bg-slate-200 w-full px-4 h-16'>
              <h1 className='flex items-center'>Next AI chat</h1>
              <UserButton showName/>
            </header>
            <main className='h-full'>
              <SignedOut>
                <div className='flex justify-center py-24'><SignIn routing='hash'/></div>
              </SignedOut>
              <SignedIn>
                {children}
              </SignedIn>
            </main>
          </body>
        </html>
        <Analytics />
      </AI>
    </ClerkProvider>
  );
}
